Achieves a successful, bare minimum AWS ECS deployment

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -1,5 +1,30 @@
 #!/bin/bash
 
-heroku container:login
-heroku container:push web
-heroku run rake db:migrate --app matchvote
+REGION=us-east-1
+ENV=$1
+
+if [ -z "$ENV" ]; then
+  echo "Environment argument missing"
+  exit 1
+fi
+
+# Login to AWS EC2 Container Registry
+$(aws ecr get-login --no-include-email)
+
+TARGET_IMAGE=788332838494.dkr.ecr.$REGION.amazonaws.com/mv-web-app:latest
+SOURCE_IMAGE=matchvote:latest
+
+echo "Stopping service task..."
+aws ecs update-service --cluster $ENV --service mv-web-app --desired-count 0
+
+echo "Building image..."
+docker build -t $SOURCE_IMAGE .
+docker tag $SOURCE_IMAGE $TARGET_IMAGE
+
+echo "Pushing image..."
+docker push $TARGET_IMAGE
+
+echo "Updating service..."
+aws ecs update-service --cluster $ENV --service mv-web-app --desired-count 1
+
+echo "Deployment successful"
